apiVersion: v1
kind: Service
metadata:
  name: calibre-web-automated
  labels:
    app.service: calibre-web-automated
spec:
  ports:
    - name: http
      port: {{ .Values.calibre_web_automated.service.port }}
      targetPort: {{ .Values.calibre_web_automated.env.CWA_PORT_OVERRIDE }}
  selector:
    app.service: calibre-web-automated
