apiVersion: v2
name: homarr
description: Vendored Homarr Helm chart for uttutu homelab
type: application
version: 1.0.0
appVersion: v1.70.0
dependencies:
  - name: homarr
    version: 8.22.0
    repository: https://homarr-labs.github.io/charts/
