apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: slskd-config
spec:
  accessModes:
    - {{ .Values.slskd.persistence.config.accessMode }}
  storageClassName: {{ .Values.slskd.persistence.config.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.slskd.persistence.config.size }}
