apiVersion: v1
kind: Service
metadata:
  name: slskd-slsk
  labels:
    app.service: slskd
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.slskd.service.loadBalancerIP }}
  ports:
    - name: slsk
      port: {{ .Values.slskd.service.slskPort }}
  selector:
    app.service: slskd
